default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: pedagogically_website_development

test:
  <<: *default
  database: pedagogically_website_test

staging:
  <<: *default
  database: pedagogically_website_staging
  username: <%= Rails.application.credentials.STAGING_DB_USERNAME %>
  password: <%= Rails.application.credentials.STAGING_DB_PASSWORD %>

production:
  <<: *default
  database: pedagogically_website_production
  username: <%= Rails.application.credentials.PRODUCTION_DB_USERNAME %>
  password: <%= Rails.application.credentials.PRODUCTION_DB_PASSWORD %>

